# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 127a0e766e47bcf7d52b94f2ff76dbb600d203fb1067dc02c9bae4c7966375ead628feb1b2273acae5b67d62dc1ee40bd8defb335b03b2b22b97bff124bc66c2

test:
  secret_key_base: 153c728e8296e67e415b235fea1ea427932aa19e7a4ffec9129ac5fc3fbe14393674d037f667d52136e8b2aec93e158e44d495ccf7680b7dc94a87e5b503e29c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
